indent-width = 4
line-length = 128
target-version = "py312"
unsafe-fixes = true
preview=false

[lint]
exclude = ["build", "dist", "venv"]
select = ["ALL"]
ignore = [
    "E701"
]

[lint.per-file-ignores]
"tests/**/*.py" = ["D", "S101", "PLR", "INP", "ANN", "ARG", "SLF", "PLW1641"]
"examples/**/*.py" = ["D", "UP", "T"]
"src/herogold/supports.py" = ["D"] # Ignore docstring on protocols.

[format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false
